controller_manager:
  ros__parameters:
    update_rate : 100
  # Publish all joint states -----------------------------------
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

  # Position Controllers --------------------------------------
joint_trajectory_controller:
  ros__parameters:
    joints:
      - body_coxa1_joint
      - body_coxa2_joint
      - body_coxa3_joint
      - body_coxa4_joint
      - body_coxa5_joint
      - body_coxa6_joint
      - coxa1_femur1_joint
      - coxa2_femur2_joint
      - coxa3_femur3_joint
      - coxa4_femur4_joint
      - coxa5_femur5_joint
      - coxa6_femur6_joint
      - femur1_tibia1_joint
      - femur2_tibia2_joint
      - femur3_tibia3_joint
      - femur4_tibia4_joint
      - femur5_tibia5_joint
      - femur6_tibia6_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    constraints:
      goal_time: 1.0
    limits:
      max_velocity: 1.0
      max_acceleration: 2.0